import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import dynamic from 'next/dynamic'

const Navbar = dynamic(() =>import('../../components/Navbar'))
const Footer = dynamic(() => import('../../components/Footer'))


const  Details = ({data}) =>  {
  return (
    <div className={styles.container} data-testid="detail-container">
      <Head>
        <title>DigitSense Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar/>
        <h1 className={styles.title}>
          {data[0].name}
        </h1>
        <div className={styles.picture}>
          <Image src={data[0].image} alt="Minimalist" width={800} height={400}/>
        </div>
        <div style={{width: '50%', textAlign: 'center'}}>
        <p className={styles.text}>
                {data[0].content}
            </p>
        </div>

      </main>
    <Footer/>
    </div>
  )
}
export const getStaticProps= async ({ params }) => {
    const response = await fetch('https://my-json-server.typicode.com/jackbloo/blogDB/posts')
    const responseData = await response.json()
    const filter = responseData.filter((el,id) => el.name === params.id)
    return {props:{data: filter}}
  };
  
  export const getStaticPaths = async () => {
    const response = await fetch('https://my-json-server.typicode.com/jackbloo/blogDB/posts')
    const responseData = await response.json()
    const paths = responseData.map((data) => `/blogs/${data.name}`)
    return {
    paths,
    fallback: true}
  };
export default Details
