import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const Navbar = dynamic(() =>import('../components/Navbar'))
const Footer = dynamic(() => import('../components/Footer'))
const Profile = dynamic(() => import('../components/Profile'))


export default function AboutUs() {
    const data = [{name:"Harry Maguire", role:"Chief Executive Officer (CEO)", content:" Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus.", image:"https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"}, {name:"Jadon Sancho", role:"Chief Technology Officer (CTO)", content:" Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus.", image:"https://images.unsplash.com/flagged/photo-1553642618-de0381320ff3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"}]
  return (
    <div className={styles.container}>
      <Head>
        <title>DigitSense Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar title="about"/>
        <h1 className={styles.title}>
          About this blog
        </h1>
        <div className={styles.profileContainer}>
            {data.map((el,id) => <Profile data={el} key={`${el.name} - ${id}`}/>)}
        </div>
      </main>
    <Footer/>
    </div>
  )
}
