import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const Navbar = dynamic(() =>import('../components/Navbar'))
const Footer = dynamic(() => import('../components/Footer'))
const Card = dynamic(() => import('../components/Card'))

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>DigitSense Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Navbar title=""/>
        <h1 className={styles.title}>
          Welcome to DigitSense Next Blog
        </h1>
        <div className={styles.picture}>
          <Image src="https://images.unsplash.com/photo-1553877522-43269d4ea984?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="Minimalist" width={800} height={400}/>
        </div>
        <div className={styles.grid}>
          {props.data.map((el,id) => <Card data={el} key={`${el.name} - ${id}`}/>)}
        </div>
      </main>
      <Footer/>
    </div>
  )
}

export const getStaticProps= async (props) => {
  const response = await fetch('https://my-json-server.typicode.com/jackbloo/blogDB/posts')
  const responseData = await response.json()
  return {props:{data: [...responseData]}}
};
